### ISSUE TITLE
TV appears in Homebridge but not Homekit.

### ISSUE THREAD

**Issue by ufatz** [AntonioMeireles/homebridge-vieramatic#53]
TV appears in Homebridge but not Homekit.

The TV appears in the Homebridge accessories and works but it doesn't appear on Homekit.
In the Homebridge hub on the home app it doesn't appear. I have tried to add it as an accessory but it doesn't appear.

```json
 "bridge": {
        "name": "Homebridge 9E73",
        "username": "0E:FA:99:38:9E:73",
        "port": 51317,
        "pin": "907-89-450"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Sonos",
            "alarms": false,
            "forceS2": true,
            "leds": false,
            "service": "light",
            "speakers": false,
            "platform": "ZP"
        },
        {
            "tvs": [
                {
                    "friendlyName": "TV",
                    "ipAddress": "192.168.2.40",
                    "mac": "a8-13-74-78-44-4d",
                    "hdmiInputs": [
                        {
                            "id": "1",
                            "name": "AppleTV"
                        },
                        {
                            "id": "3",
                            "name": "Switch"
                        }
                    ],
                    "customVolumeSlider": false
                }
            ],
            "platform": "PanasonicVieraTV"
        }
    ]
}
```
TV is Panasonic Viera TX-50CX800B 

Homebridge v1.1.7

Node.js Version | v14.15.3
NPM  v6.14.9

Running on MAC Mini 2014.

Cheers
Ian

**Comment by AntonioMeireles** [comment]
humm, that's odd - can you try to remove your Homekit bridge from homekit and add it again to check if issue persists ?

thanks in advance!

**Comment by jeatrexs** [comment]
Hi, i just set up my first homebridge on my raspberry and i can also confirm the problem described by @ufatz. My TV shows up in the homebridge under 'devices' but won't appear under Home-App in iOS / Home-Widget. I already tried to remove the homebridge from my home in the Home app and readded it, but it did not work out. It's still not there.

Thanks,
patrick

**Comment by AntonioMeireles** [comment]
@jeatrexs 

Thanks for reporting! so, **after** adding the homekit bridge to Home App, **when you do an "Add Accessory"  the TV does not appear there / isn't discovered ?** Could you please provide the homebridge startup logs ? something is going wrong ... also, please provide data about your homebridge / network setup - OS / arch / versions / etc.

**Comment by jeatrexs** [comment]
Hi @AntonioMeireles,

sorry, my bad. I already edited my last post.
I thought, the device comes up automatically, because it was like that with other plugins. Sorry i'm still a beginner.

Thank you!

**Comment by AntonioMeireles** [comment]
@jeatrexs 

glad it's sorted :-) it has to be that way - only way to support lucky users with multiple TVs :-)
Happy new Year!

**Comment by AntonioMeireles** [comment]
reopening until we hear from @ufatz which may have a different issue.

**Comment by jeatrexs** [comment]
I understand. Thank you a lot, Happy new year to you also! 

> 
> 
> @jeatrexs
> 
> glad it's sorted :-) it has to be that way - only way to support lucky users with multiple TVs :-)
> Happy new Year!

I understand. Thank you a lot, Happy new year to you also!

**Comment by ufatz** [comment]
@ufatz here
So the weirdness continues.
As you suggested I have removed the home bridge and reinstalled it in Home. When I tried to add accessory the TV does not appear. However if I ask Siri to turn the TV on, it does! And also off! I just don’t have a button for it in the Home app?!






Setup Payload:
X-HM://0024YZHOQ313B
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 907-89-450 │     
    └────────────┘     
                       
[12/31/2020, 6:28:40 PM] Homebridge is running on port 51317.
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [192.168.2.10]: request 1: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [192.168.2.10]: request 2: POST /ZoneGroupTopology/Control GetZoneGroupState
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [192.168.2.11]: request 1: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [192.168.2.11]: request 2: POST /ZoneGroupTopology/Control GetZoneGroupState
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_5CAAFD2600C401400 [192.168.2.12]: request 1: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_5CAAFD2600C401400 [192.168.2.12]: request 2: POST /ZoneGroupTopology/Control GetZoneGroupState
found a 'Panasonic VIErA' TV (TX-50CX800B) at '192.168.2.40' .

[12/31/2020, 6:28:40 PM] [PanasonicVieraTV] {
  "friendlyName": "TV",
  "ipAddress": "192.168.2.40",
  "mac": "a8-13-74-78-44-4d",
  "hdmiInputs": [
    {
      "id": "1",
      "name": "AppleTV"
    },
    {
      "id": "3",
      "name": "Switch"
    }
  ],
  "customVolumeSlider": false
}
[12/31/2020, 6:28:40 PM] [PanasonicVieraTV] Restoring TV
[12/31/2020, 6:28:40 PM] [PanasonicVieraTV] successfully loaded TV
[12/31/2020, 6:28:40 PM] TV is running on port 58627.
[12/31/2020, 6:28:40 PM] Please add [TV] manually in Home app. Setup Code: 907-89-450
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [192.168.2.10]: request 2: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [192.168.2.10]: TV Speaker: Sonos Beam (S14) v12.2.2
[12/31/2020, 6:28:40 PM] [Sonos] listening on http://192.168.2.50:58628/notify
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: associated S2 zone player
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: request 3: SUBSCRIBE /ZoneGroupTopology/Event
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [192.168.2.11]: request 2: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [192.168.2.11]: Dining Room: Sonos Play:3 (S3) v12.2.2
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: probing done (2 jobs remaining)
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_5CAAFD2600C401400 [192.168.2.12]: request 2: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_5CAAFD2600C401400 [192.168.2.12]: Kitchen: Sonos Play:1 (S1) v12.2.2
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: probing done (1 jobs remaining)
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: request 3: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: probing done (0 jobs remaining)
[12/31/2020, 6:28:40 PM] [Sonos] found 3 S2 zone players in 3 zones
[12/31/2020, 6:28:40 PM] [Sonos] ├─ Dining Room
[12/31/2020, 6:28:40 PM] [Sonos] │  └─ RINCON_B8E937DA610E01400 [Dining Room]: Sonos Play:3 (S3) (master)
[12/31/2020, 6:28:40 PM] [Sonos] ├─ Kitchen
[12/31/2020, 6:28:40 PM] [Sonos] │  └─ RINCON_5CAAFD2600C401400 [Kitchen]: Sonos Play:1 (S1) (master)
[12/31/2020, 6:28:40 PM] [Sonos] └─ TV Speaker
[12/31/2020, 6:28:40 PM] [Sonos]    └─ RINCON_48A6B831DFB801400 [TV Speaker]: Sonos Beam (S14) (master, airPlay, tvIn)
[12/31/2020, 6:28:40 PM] [Sonos] Dining Room: Sonos accessory
[12/31/2020, 6:28:40 PM] [Sonos] Dining Room Sonos: Sonos service
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: request 3: SUBSCRIBE /GroupManagement/Event
[12/31/2020, 6:28:40 PM] [Sonos] Kitchen: Sonos accessory
[12/31/2020, 6:28:40 PM] [Sonos] Kitchen Sonos: Sonos service
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: request 3: SUBSCRIBE /GroupManagement/Event
[12/31/2020, 6:28:40 PM] [Sonos] TV Speaker: Sonos accessory
[12/31/2020, 6:28:40 PM] [Sonos] TV Speaker Sonos: Sonos service
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: request 4: SUBSCRIBE /GroupManagement/Event
[12/31/2020, 6:28:40 PM] [Sonos] initialised
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: event: NOTIFY ZoneGroupTopology/Event
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: request 4: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: event: NOTIFY GroupManagement/Event
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: request 5: SUBSCRIBE /MediaRenderer/AVTransport/Event
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: request 6: SUBSCRIBE /MediaRenderer/GroupRenderingControl/Event
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: request 3: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: request 3: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: event: NOTIFY GroupManagement/Event
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: request 4: SUBSCRIBE /MediaRenderer/AVTransport/Event
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: request 5: SUBSCRIBE /MediaRenderer/GroupRenderingControl/Event
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: event: NOTIFY GroupManagement/Event
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: request 4: SUBSCRIBE /MediaRenderer/AVTransport/Event
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: request 5: SUBSCRIBE /MediaRenderer/GroupRenderingControl/Event
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: request 5: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: event: NOTIFY MediaRenderer/AVTransport/Event
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: request 7: POST /MediaRenderer/AVTransport/Control GetRemainingSleepTimerDuration
[12/31/2020, 6:28:40 PM] [Sonos] TV Speaker Sonos: set currentTransportActions from ["Set","Stop","Pause","Play","X_DLNA_SeekTime","Next","Previous"] to ["Set","Stop","Pause","Play","X_DLNA_SeekTime","Next","Previous"]
[12/31/2020, 6:28:40 PM] [Sonos] TV Speaker Sonos: set currentValidPlayModes from ["SHUFFLE","REPEAT","REPEATONE"] to ["SHUFFLE","REPEAT","REPEATONE"]
[12/31/2020, 6:28:40 PM] [Sonos] upnp: found RINCON_B8E937DA610E01400 at 192.168.2.11
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: request 4: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: request 6: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: request 4: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: event: NOTIFY MediaRenderer/AVTransport/Event
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: request 6: POST /MediaRenderer/AVTransport/Control GetRemainingSleepTimerDuration
[12/31/2020, 6:28:40 PM] [Sonos] Dining Room Sonos: set currentTransportActions from ["Set","Stop","Pause","Play","X_DLNA_SeekTime","Next","Previous","X_DLNA_SeekTrackNr"] to ["Set","Stop","Pause","Play","X_DLNA_SeekTime","Next","Previous","X_DLNA_SeekTrackNr"]
[12/31/2020, 6:28:40 PM] [Sonos] Dining Room Sonos: set currentValidPlayModes from ["SHUFFLE","REPEAT","REPEATONE","CROSSFADE"] to ["SHUFFLE","REPEAT","REPEATONE","CROSSFADE"]
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: request 5: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: request 7: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: event: NOTIFY MediaRenderer/AVTransport/Event
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: request 6: POST /MediaRenderer/AVTransport/Control GetRemainingSleepTimerDuration
[12/31/2020, 6:28:40 PM] [Sonos] Kitchen Sonos: set currentTransportActions from ["Set","Stop","Pause","Play","X_DLNA_SeekTime","Next","Previous","X_DLNA_SeekTrackNr"] to ["Set","Stop","Pause","Play","X_DLNA_SeekTime","Next","Previous","X_DLNA_SeekTrackNr"]
[12/31/2020, 6:28:40 PM] [Sonos] Kitchen Sonos: set currentValidPlayModes from ["SHUFFLE","REPEAT","REPEATONE","CROSSFADE"] to ["SHUFFLE","REPEAT","REPEATONE","CROSSFADE"]
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: request 5: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: event: NOTIFY MediaRenderer/GroupRenderingControl/Event
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: request 6: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: request 6: status 200 OK
[12/31/2020, 6:28:40 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: event: NOTIFY MediaRenderer/GroupRenderingControl/Event
[12/31/2020, 6:28:41 PM] [Sonos] upnp: found RINCON_48A6B831DFB801400 at 192.168.2.10
[12/31/2020, 6:28:41 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: event: NOTIFY MediaRenderer/GroupRenderingControl/Event
[12/31/2020, 6:28:41 PM] [Sonos] upnp: found RINCON_5CAAFD2600C401400 at 192.168.2.12
[12/31/2020, 6:28:41 PM] [Sonos] npm registry request 1: GET /homebridge-zp/latest
[12/31/2020, 6:28:42 PM] [Sonos] npm registry request 1: 200 OK
[12/31/2020, 6:28:42 PM] [Sonos] latest version: homebridge-zp v1.1.4
[12/31/2020, 6:28:45 PM] [Sonos] upnp: search done
[12/31/2020, 6:29:11 PM] [Sonos] flush cachedAccessories
[12/31/2020, 6:29:11 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: lastSeen: 31s ago at 192.168.2.11, bootSeq: 2
[12/31/2020, 6:29:11 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: lastSeen: 30s ago at 192.168.2.12, bootSeq: 2
[12/31/2020, 6:29:11 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: lastSeen: 23s ago at 192.168.2.10, bootSeq: 73
[12/31/2020, 6:29:30 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: event: NOTIFY MediaRenderer/AVTransport/Event
[12/31/2020, 6:29:30 PM] [Sonos] TV Speaker Sonos: set Track from "Son Of A Preacher Man" to "(Sittin' On) the Dock of the Bay"
[12/31/2020, 6:29:30 PM] [Sonos] TV Speaker Sonos: set currentTransportActions from ["Set","Stop","Pause","Play","X_DLNA_SeekTime","Next","Previous"] to ["Set","Stop","Pause","Play","X_DLNA_SeekTime"]
[12/31/2020, 6:29:31 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: event: NOTIFY MediaRenderer/AVTransport/Event
[12/31/2020, 6:29:31 PM] [Sonos] TV Speaker Sonos: set currentTransportActions from ["Set","Stop","Pause","Play","X_DLNA_SeekTime"] to ["Set","Stop","Pause","Play","X_DLNA_SeekTime","Next","Previous"]
[12/31/2020, 6:30:34 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: request 7: POST /MediaRenderer/AVTransport/Control GetRemainingSleepTimerDuration
[12/31/2020, 6:30:34 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: request 8: POST /MediaRenderer/AVTransport/Control GetRemainingSleepTimerDuration
[12/31/2020, 6:30:34 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: request 7: POST /MediaRenderer/AVTransport/Control GetRemainingSleepTimerDuration
[12/31/2020, 6:30:34 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: request 8: status 200 OK
[12/31/2020, 6:30:34 PM] [Sonos] TV Speaker Sonos: get Remaining Duration: return 0s
[12/31/2020, 6:30:34 PM] [PanasonicVieraTV] (getVolume) unable to get volume from TV...
[12/31/2020, 6:30:34 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: request 7: status 200 OK
[12/31/2020, 6:30:34 PM] [Sonos] Kitchen Sonos: get Remaining Duration: return 0s
[12/31/2020, 6:30:34 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: request 7: status 200 OK
[12/31/2020, 6:30:34 PM] [Sonos] Dining Room Sonos: get Remaining Duration: return 0s
[12/31/2020, 6:30:34 PM] [PanasonicVieraTV] (getMute) is true
[12/31/2020, 6:30:34 PM] [PanasonicVieraTV] (setPowerStatus) 1 false
[12/31/2020, 6:30:34 PM] [PanasonicVieraTV] sending WOL packets to awake TV
[12/31/2020, 6:30:36 PM] [PanasonicVieraTV] Turned TV ON
[12/31/2020, 6:30:37 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: request 9: POST /MediaRenderer/AVTransport/Control GetRemainingSleepTimerDuration
[12/31/2020, 6:30:37 PM] [Sonos] RINCON_5CAAFD2600C401400 [Kitchen]: request 8: POST /MediaRenderer/AVTransport/Control GetRemainingSleepTimerDuration
[12/31/2020, 6:30:37 PM] [Sonos] RINCON_B8E937DA610E01400 [Dining Room]: request 8: POST /MediaRenderer/AVTransport/Control GetRemainingSleepTimerDuration
[12/31/2020, 6:30:37 PM] [Sonos] RINCON_48A6B831DFB801400 [TV Speaker]: request 9: status 200 OK
[12/31/2020, 6:30:37 PM] [Sonos] TV Speaker Sonos: get Remaining Duration: return 0s


Sorry to be a pain.
If there is anymore info that you need please let me know, oh and Happy New Year.
Cheers
Ian

**Comment by AntonioMeireles** [comment]
way odd, on the TV remote app - does the TV appear ?

**Comment by ufatz** [comment]
Yes, 


Ian Rogers

**Comment by cschrone** [comment]
Hey together,
I have the same problem since last year like @ufatz .
It startet from the moment where i once deleted my TV manually in homebridge. After that it appears as before in homebridge. But it is not possible to readd that TV by the way using the automatic way in HomeKit „add device“.

Reinstalling the plugin, changing the config, readding the bridge to HomeKit, deactivating and reactivating the remote option in tv settings didn‘t help. The latest way i tried was to add a second Tv with another name - same problem here.

Thanks so far

**Comment by AntonioMeireles** [comment]
@ufatz looks like somehow  a local cosmetic issue in IOS side (as the plugin is actually recognized) ... could you please try to remove you homebridge bridge from ios' home.app and add it again to see if it makes a change ?

@cschrone remove your homebridge bridge from home.app in IOS and then add it again. Please check if this is your issue.

thanks both for your patience!

**Comment by msbc42** [comment]
I'm seeing the same issue - accessories in Homebridge but not Home app. Deleted my bridge from iOS and re-added to Home. Still no accessories.

**Comment by AntonioMeireles** [comment]
@msbc42, @ufatz 

what homebridge version ?  `1.2.5` or `1.1.7` ?

**Comment by cschrone** [comment]
As mentioned before i already tried this solution. Like @msbc42 said the problem seems to be somewhere else.
I tested it on two Panasonic TVs. Once on a FZW804 and now on a HZW984. After removing the FZW804 manually in home.app it never appeared in the add-Assistant or somewhere in the app. Only in Homebridge.
By adding the HZW984 it was no Problem to add it. Still till the moment i again removed it because there were some problem with renaming.

**Comment by ufatz** [comment]
I am running 1.1.7
Removing  homebridge from Home App does not hangs anything. It still cannot find the tv as an accessory to add.

**Comment by msbc42** [comment]
I am also on 1.1.7

**Comment by AntonioMeireles** [comment]
could you both give a try to `homebridge-vieramatic@2.0.15` that i just published to see if it makes a difference ?

thanks in advance and a great weekend!

**Comment by cschrone** [comment]
Good evening,
I found a way that solved my problem.
It’s a cache problem.

With the following steps i solved it by using homebridge-config-ui-x by oznu

1. Open Web UI and go to homebridge settings
2. Select in the area reset something like „ Decouple bridges / cameras / TV / external accessories“
3. Choose your tv and delete it.
4. Restart homebridge
5. Go to home app and add new device. It should appear like expected.

Please try and let me know.
Before that i updated the plug-in by @AntonioMeireles 
I‘m not sure if that has something to do with.

**Comment by msbc42** [comment]
2.0.15 Plug-in did not solve the issue on it's own. After updating still no accessory in Home. Cleared the cache as suggested by @cschrone and was able to add the accessory in Home app.

Should there be a seperate accessory for changing Volume as there is in Homebridge?

**Comment by AntonioMeireles** [comment]
Closing, as things now well understood, and root cause not in plugin side. 

please reopen if somehow, previous paragraph wrong. 

thanks all for your patience
